### ISSUE TITLE
Inconsistent Typing for Joined Field in Supabase

### ISSUE THREAD

**Issue by cptcrunchy** [supabase/postgrest-js#546]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have added a link to a REPL, [HERE](https://replit.com/@cptcrunchy/SelfreliantObviousPlan?v=1) along with a screenshot.
The example code expects the `created_by` field in the query result to be a single object containing employee details (id and full_name). However, the type definition `({ id: any; full_name: any; }[])` suggests it's an array of employees. This mismatch causes a typing error when working with the data.

**Why it happens**:

The !report_created_by_fkey syntax likely defines a relationship between tables, but the return type might not be explicitly set to a single object.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to The REPL [link](https://replit.com/@cptcrunchy/SelfreliantObviousPlan?v=1) 
2. Enter your Project URL and ANON key into the createClient instance.
3. Create the table schemas provided in `$lib/db`
4. When hovering over `data` the return type def is an array of objects.

## Expected behavior

The result type def should be a single object for the field `created_by`.

## Screenshots

![Screenshot 2024-06-17 at 15 57 57](https://github.com/supabase/supabase/assets/8497282/a751bf0a-66a8-4d36-ac3f-e75cf7c02c88)

## System information

- OS: macOS
- Version of supabase-js: 2.42.7
- Version of Node.js: 18.20.3

**Comment by jdgamble555** [comment]
@soedirgo - This is the same issue opened MANY times and still needs to be fixed.
- https://github.com/supabase/postgrest-js/issues/512
- https://github.com/supabase/postgrest-js/issues/536
- https://github.com/supabase/postgrest-js/issues/509
- https://github.com/supabase/postgrest-js/issues/471
- https://github.com/supabase/postgrest-js/issues/434
- https://github.com/supabase/postgrest-js/issues/408
- https://github.com/supabase/postgrest-js/issues/406
- https://github.com/supabase/postgrest-js/issues/355

We have 8 different repos all for the same problem. JOINS do not have the correct typing. This needs to be moved up the ladder as a PRIORITY.

J

**Comment by jdgamble555** [comment]
@soedirgo - Can we please get this looked at? Every single join is effected, there are hundreds of complaints. Please raise this issue to the top of the list!

Thanks,

J

**Comment by FernandoI7** [comment]
+1

**Comment by osilviotti** [comment]
I've also encountered this recently.

In case it's helpful, querying the table directly returned the correct type for the relation (e.g. `{ id: string; } | null`), but calling an RPC function that returned a `SETOF` the same table returned the incorrect type (e.g. `{ id: string }[]`). The field types in the Supabase generated `Database` are identical between the table and the function so I don't think there's any issue there.

I had a quick look at the types and the direct query uses `PostgrestQueryBuilder` where the RPC version uses `PostgrestFilterBuilder` in a similar way. I don't know if that's related and there's some difference in inferring the relationships within them, or if I'm barking up the wrong tree completely with this.

**Comment by jdgamble555** [comment]
@osilviotti - RPC functions are a different problem and should be in a new post. I don't want the Supabase staff to get off topic from the issue at hand.

I don't know your use case, but most MOST join cases do not work as expected. You can scroll through the issues listed above.

J

**Comment by alfredomariamilano** [comment]
It's not ideal, but for the time being, I'm fixing it like so:
```ts
supabase.from('posts').select('author:profiles!user_id(username)' as 'author:profiles!screens_user_id_fkey(username)')
```
Types are inferred correctly if you use the foreign key constraint's name, which should help solve this.

**Comment by clement-faure** [comment]
Same issue here following documentation. I've been able to find a workaround using this to populate one to one relationship.

`created_by: employees !inner(*)`

**Comment by soedirgo** [comment]
I couldn't reproduce the issue in this [repo](https://github.com/soedirgo/repro-join-typings) - here's the types I'm getting:

<img width="1143" alt="Screenshot 2024-09-10 at 6 13 10 PM" src="https://github.com/user-attachments/assets/b07ae1a1-5620-4e2a-be2b-e792fc0b39b9">

If anyone can reproduce the issue, can you share the contents of your generated types (`database.types.ts`)?

**Comment by alfredomariamilano** [comment]
> I couldn't reproduce the issue in this [repo](https://github.com/soedirgo/repro-join-typings) - here's the types I'm getting:
> 
> <img alt="Screenshot 2024-09-10 at 6 26 09 PM" width="1143" src="https://private-user-images.githubusercontent.com/31685197/366146675-fb21c3d0-959b-4b72-8218-38a9cb7028fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk4NzcsIm5iZiI6MTcyNjA0OTU3NywicGF0aCI6Ii8zMTY4NTE5Ny8zNjYxNDY2NzUtZmIyMWMzZDAtOTU5Yi00YjcyLTgyMTgtMzhhOWNiNzAyOGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEwMTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYjZkYWIwYjZlYzFmOGVjNDQyYWMwYzJmNGYyNmIyYzBiNzhmMjEwYzliYmFhODVjOTVmZDliODljYzEwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRK5_uKhEpC24cGNq1zhXZlBTz2BiKxR_tkDeLLUlDg">
> If anyone can reproduce the issue, can you share the contents of your generated types (`database.types.ts`)?

The types work if you use the foreignKeyName, but the request will fail because it expects the column's name.
In my example above (`'author:profiles!user_id(username)' as 'author:profiles!screens_user_id_fkey(username)'`), the column holding the foreign key is `user_id`, but the name of the foreign key is `screens_user_id_fkey`. postgrest expects the name of the column to run the actual query, but it expects the name of the foreign key for the types.

**Comment by jdgamble555** [comment]
@soedirgo - I have created an example REPO with all the problems I can think of right now.

```ts
// DOES NOT WORK, 'users' is possibly null, clearly there is a required FK
const test1 = await supabase.from('posts').select('users(*)')

// DOES NOT WORK, 'user_id' is empty array
const test2 = await supabase.from('posts').select('user_id(*)');

// DOES NOT WORK, 'user' is empty array
const test3 = await supabase.from('posts').select('user:user_id(*)');

// DOES NOT WORK, 'users' is array instead of single
const test4 = await supabase.from('posts').select('users!user_id(*)');

// DOES NOT WORK, 'user' is array instead of single
const test5 = await supabase.from('posts').select('user:users!user_id(*)');
```

See [repo](https://github.com/jdgamble555/supabase-types/blob/master/src/lib/index.ts).

J

**Comment by avallete** [comment]
Hey there,

I'm currently working on this issue in PR #554. I've added more tests to ensure better consistency between runtime behavior and type inference results. Hopefully, this will cover more cases, although I'm not certain it will handle all of them—there are quite a few edge cases to consider.

Additionally, I wonder if it might be worth adding more "hinting" for type inference in the database introspection results. For example, in cases where the result of a foreign key (FK) is nullable when it shouldn't be, it might be easier to resolve these cases by providing this information directly inside the "relationship" object. This approach could potentially avoid a convoluted type search across relations and table columns to check if the value of the holding column can be null or not.

So far, I still have six divergences between types and runtime values in the test scenarios I’ve set up. Most of these involve relation results being possibly null when they shouldn't be, and some are due to "relation aliasing." Depending on whether the user uses a direct foreign key name, a column name, or the destination table (in cases where there is a single relation between `table1` and `table2`), the parser fails to determine the correct result type.

@soedirgo, I believe most of these issues could be addressed by slightly augmenting the data we pull during introspection (e.g., handling the nullable issue). Would this be something worth considering? It would probably require users to rebuild their types and could result in a breaking change between pre- and post-version for the query parser. What do you think?

**Comment by avallete** [comment]
Hey everyone !

We've reworked the result inference in `postgrest-js` to address the typing issues mentioned above. The changes are available in a canary release, and we're actively seeking your feedback.

To test it out, update your `supabase-js` to version `2.46.0-rc.1` (which includes `postgrest-js` `1.17.0-rc.1`):

```bash
npm install supabase-js@2.46.0-rc.1
```

Please let us know if you encounter any issues, especially with retro-compatibility, so we can finalize it for the next release.

**Comment by alfredomariamilano** [comment]
> Hey everyone !
> 
> We've reworked the result inference in `postgrest-js` to address the typing issues mentioned above. The changes are available in a canary release, and we're actively seeking your feedback.
> 
> To test it out, update your `supabase-js` to version `2.46.0-rc.1` (which includes `postgrest-js` `1.17.0-rc.1`):
> 
> ```shell
> npm install supabase-js@2.46.0-rc.1
> ```
> 
> Please let us know if you encounter any issues, especially with retro-compatibility, so we can finalize it for the next release.

Hi @avallete! Sorry for the late reply and thanks for the work on the RC. I've tested it in my project for its use-cases and it works like a charm and infers the correct types!

**Comment by avallete** [comment]
The fix has been released in `supabase-js` v2.46.0. I'm closing this issue, but feel free to reopen or open a new issue if you encounter any further errors.

**Comment by StevieBoyWonder** [comment]
Can this be reopened. Im still facing this issue, and I looking at the changelog, this was reverted.

**Comment by avallete** [comment]
> Can this be reopened. Im still facing this issue and looking at the changelog this was reverted.

Yes it has been reverted as it caused unexpected regressions with previous version.

FYI: We are working on fixing those and carry on with the patch. @StevieBoyWonder in the meantime if there is no regression on your codebase you can use `2.46.0` which should fix this issue for you.

**Comment by jdgamble555** [comment]
@avallete - Are you guys fixing this still? Everything was working fine before you reverted it...

**Comment by avallete** [comment]
> @avallete - Are you guys fixing this still? Everything was working fine before you reverted it...

Hey ! Thanks for the feedback and yes we are. 

We think that we managed to fix most of the regressions that had been reported so this should land pretty soon.

Meanwhile you can use the new types inference version through the "rc" releases of `supabase-js`

**Comment by avallete** [comment]
@jdgamble555 Happy to tell you that we just released [v2.47.8](https://github.com/supabase/supabase-js/releases/tag/v2.47.8) that include the typing inference rework which should fix the inconsistents typing on joined fields.

**Comment by jdgamble555** [comment]
@avallete - Could you look at this, I believe this broke RPC function typing, which should be an easy fix I would imagine.

https://github.com/supabase/postgrest-js/issues/602

J
